extends Node2D

var HEALTH = 100;
var MONEY  = 100;
var default_font : Font = ThemeDB.fallback_font;

# Called when the node enters the scene tree for the first time.
func _ready():
	pass # Replace with function body.

func _process(delta):
	queue_redraw()
	
func _draw():
	draw_string(default_font, Vector2(8, 16), "Health: %d" % HEALTH, 0, -1, 12)
	draw_string(default_font, Vector2(8, 32), "Money: %d" % MONEY, 0, -1, 12)

func set_money(value):
	MONEY += value
	
func set_health(value):
	HEALTH += value

func _input(event):
	if event.is_action_pressed("pad_left"):
		print("pad_left pressed")
	if event.is_action_pressed("pad_down"):
		print("pad_down pressed")
	if event.is_action_pressed("pad_right"):
		print("pad_right pressed")
	if event.is_action_pressed("pad_up"):
		print("pad_up pressed")
	if event.is_action_pressed("pad_lb"):
		print("pad_lb pressed")
	if event.is_action_pressed("pad_lt"):
		print("pad_lt pressed")
	if event.is_action_pressed("pad_ls"):
		print("pad_ls pressed")
	if event.is_action_pressed("pad_rb"):
		print("pad_rb pressed")
	if event.is_action_pressed("pad_rt"):
		print("pad_rt pressed")
	if event.is_action_pressed("pad_rs"):
		print("pad_rs pressed")
	if event.is_action_pressed("pad_face_a"):
		print("pad_face_a pressed")
	if event.is_action_pressed("pad_face_b"):
		print("pad_face_b pressed")
	if event.is_action_pressed("pad_face_x"):
		print("pad_face_x pressed")
	if event.is_action_pressed("pad_face_y"):
		print("pad_face_y pressed")
	if event.is_action_pressed("pad_select"):
		print("pad_select pressed")
	if event.is_action_pressed("pad_start"):
		print("pad_start pressed")
	if event.is_action_pressed("pad_ls_x"):
		print("pad_ls_x pressed")
	if event.is_action_pressed("pad_ls_y"):
		print("pad_ls_y pressed")
	if event.is_action_pressed("pad_rs_x"):
		print("pad_rs_x pressed")
	if event.is_action_pressed("pad_rs_y"):
		print("pad_rs_y pressed")
	if event.is_action_pressed("pad_home"):
		print("pad_home pressed")
	if event.is_action_pressed("pad_paddle_1"):
		print("pad_paddle_1 pressed")
	if event.is_action_pressed("pad_paddle_2"):
		print("pad_paddle_2 pressed")
	if event.is_action_pressed("pad_paddle_3"):
		print("pad_paddle_3 pressed")
	if event.is_action_pressed("pad_paddle_4"):
		print("pad_paddle_4 pressed")
	if event.is_action_pressed("pad_ps_touchpad"):
		print("pad_ps_touchpad pressed")
	if event.is_action_pressed("pad_share"):
		print("pad_share pressed")
	if event.is_action_pressed("mouse_left"):
		print("mouse_left pressed")
	if event.is_action_pressed("mouse_right"):
		print("mouse_right pressed")
	if event.is_action_pressed("mouse_wheel"):
		print("mouse_wheel pressed")
	if event.is_action_pressed("mouse_wheel_up"):
		print("mouse_wheel_up pressed")
	if event.is_action_pressed("mouse_wheel_down"):
		print("mouse_wheel_down pressed")
	if event.is_action_pressed("mouse_wheel_left"):
		print("mouse_wheel_left pressed")
	if event.is_action_pressed("mouse_wheel_right"):
		print("mouse_wheel_right pressed")
	if event.is_action_pressed("mouse_thumb_1"):
		print("mouse_thumb_1 pressed")
	if event.is_action_pressed("mouse_thumb_2"):
		print("mouse_thumb_2 pressed")
	if event.is_action_pressed("key_a"):
		print("key_a pressed")
	if event.is_action_pressed("key_b"):
		print("key_b pressed")
	if event.is_action_pressed("key_c"):
		print("key_c pressed")
	if event.is_action_pressed("key_d"):
		print("key_d pressed")
	if event.is_action_pressed("key_e"):
		print("key_e pressed")
	if event.is_action_pressed("key_f"):
		print("key_f pressed")
	if event.is_action_pressed("key_g"):
		print("key_g pressed")
	if event.is_action_pressed("key_h"):
		print("key_h pressed")
	if event.is_action_pressed("key_i"):
		print("key_i pressed")
	if event.is_action_pressed("key_j"):
		print("key_j pressed")
	if event.is_action_pressed("key_k"):
		print("key_k pressed")
	if event.is_action_pressed("key_l"):
		print("key_l pressed")
	if event.is_action_pressed("key_m"):
		print("key_m pressed")
	if event.is_action_pressed("key_n"):
		print("key_n pressed")
	if event.is_action_pressed("key_o"):
		print("key_o pressed")
	if event.is_action_pressed("key_p"):
		print("key_p pressed")
	if event.is_action_pressed("key_q"):
		print("key_q pressed")
	if event.is_action_pressed("key_r"):
		print("key_r pressed")
	if event.is_action_pressed("key_s"):
		print("key_s pressed")
	if event.is_action_pressed("key_t"):
		print("key_t pressed")
	if event.is_action_pressed("key_u"):
		print("key_u pressed")
	if event.is_action_pressed("key_v"):
		print("key_v pressed")
	if event.is_action_pressed("key_w"):
		print("key_w pressed")
	if event.is_action_pressed("key_x"):
		print("key_x pressed")
	if event.is_action_pressed("key_y"):
		print("key_y pressed")
	if event.is_action_pressed("key_z"):
		print("key_z pressed")
	if event.is_action_pressed("key_1"):
		print("key_1 pressed")
	if event.is_action_pressed("key_2"):
		print("key_2 pressed")
	if event.is_action_pressed("key_3"):
		print("key_3 pressed")
	if event.is_action_pressed("key_4"):
		print("key_4 pressed")
	if event.is_action_pressed("key_5"):
		print("key_5 pressed")
	if event.is_action_pressed("key_6"):
		print("key_6 pressed")
	if event.is_action_pressed("key_7"):
		print("key_7 pressed")
	if event.is_action_pressed("key_8"):
		print("key_8 pressed")
	if event.is_action_pressed("key_9"):
		print("key_9 pressed")
	if event.is_action_pressed("key_0"):
		print("key_0 pressed")
	if event.is_action_pressed("key_esc"):
		print("key_esc pressed")
	if event.is_action_pressed("key_tilde"):
		print("key_tilde pressed")
	if event.is_action_pressed("key_tab"):
		print("key_tab pressed")
	if event.is_action_pressed("key_caps"):
		print("key_caps pressed")
	if event.is_action_pressed("key_shift"):
		print("key_shift pressed")
	if event.is_action_pressed("key_ctrl"):
		print("key_ctrl pressed")
	if event.is_action_pressed("key_super"):
		print("key_super pressed")
	if event.is_action_pressed("key_alt"):
		print("key_alt pressed")
	if event.is_action_pressed("key_space"):
		print("key_space pressed")
	if event.is_action_pressed("key_enter"):
		print("key_enter pressed")

